### ISSUE TITLE
`An activity without a UI must call finish() before onResume() completes`

### ISSUE THREAD

**Issue by noties** [hokolinks/hoko-android#13]
That's it. I think it pretty self-explanatory. Android 6.0

Just in case, here is the stacktrace:

```
java.lang.RuntimeException: Unable to resume activity {com.glovo.dev/com.hokolinks.activity.HokoActivity}: java.lang.IllegalStateException: Activity {com.glovo.dev/com.hokolinks.activity.HokoActivity} did not call finish() prior to onResume() completing
                                                                   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
                                                                   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                Caused by: java.lang.IllegalStateException: Activity {com.glovo.dev/com.hokolinks.activity.HokoActivity} did not call finish() prior to onResume() completing
                                                                   at android.app.Activity.performResume(Activity.java:6324)
                                                                   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
                                                                   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134) 
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481) 
                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by noties** [comment]
Ah, I've used `Theme.NoDisplay` for Hoko activities. Using `Theme.Translucent.NoTitleBar` for api 23 works fine
